version: '3.8'

services:

  db:
    container_name: "crc_postgres"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=crc2025
      - POSTGRES_USER=crc2025
    ports:
      - '5400:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data